AWSTemplateFormatVersion: '2010-09-09'
Description: Sample EC2 instance using CloudFormation

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-068c0051b15cdb816
      InstanceType: t3.micro
      Tags:
        - Key: Name
          Value: Jenkins-CF-Instance